version: '3.4'

volumes:
  postgres-data:

services:
  postgres:
    container_name: db
    image: postgres:13-alpine
    restart: unless-stopped
    tty: true
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
